import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/layout/nav/navbar";
import Categories from "./Component/layout/categories/Sidebar";
import Filterpage from "./Component/context";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
      <Filterpage>
          <Navbar />
          <div className="flex pl-0 h-full pt-24">
            <div className="w-48 border-gray-300 p-2 h-dvh z-10 fixed border-r">
              <Categories />
            </div>
            <div className="ml-52"></div>
            <div className="w-5/6 pb-3">{children}</div>
          </div>
       </Filterpage>
      </body>
    </html>
  );
}
